### PR TITLE
Add frame_blend option to animations

### PR DESCRIPTION
**Pull request by ElCeejo**
This PR adds the ability for frame blending with mobkits animate function. This is optional and will default to 0 if not used.

### CODE REVIEW

**Comment by TheTermos** [comment]
Ok let me test it out.

**Comment by TheTermos** [comment]
Seems ok.

I don't remember now, but I'm pretty sure I must have intentionally excluded this parameter as useless or buggy.
Can you provide some use cases for it?

**Comment by ElCeejo** [comment]
With some models it can break rotations but that's why I have it set to 0 by default, but as long as the model is parented fully there shouldn't be any issues. If you have a sleep animation this will allow for a smooth transition to the animation without needing to do a dedicated transition animation, also transitions between any other animations will look a lot less jarring.

**Comment by TheTermos** [comment]
I think it's ok to merge, thanks!

**Pull request merged**
